--
-- PostgreSQL database dump
--

\restrict Ua4RAut8IeesMGs5ScRbjtI5mPZwQCuG8lITuc7r1jPj2OL65P32NzwnNFNoS3o

-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.4

-- Started on 2026-07-15 03:31:20

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 10 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3813 (class 0 OID 0)
-- Dependencies: 10
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 351 (class 1259 OID 17618)
-- Name: producto_color; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producto_color (
    id integer NOT NULL,
    producto_id integer NOT NULL,
    nombre_color character varying(50),
    codigo_hexadecimal character varying(10)
);


ALTER TABLE public.producto_color OWNER TO postgres;

--
-- TOC entry 350 (class 1259 OID 17617)
-- Name: producto_color_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.producto_color ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.producto_color_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 355 (class 1259 OID 18014)
-- Name: producto_definitivo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producto_definitivo (
    id integer NOT NULL,
    nombre character varying(255) NOT NULL,
    marca character varying(255) NOT NULL,
    categoria character varying(255),
    almacenamiento character varying(255),
    ram character varying(255),
    procesador character varying(255),
    precio_normal double precision,
    precio double precision NOT NULL,
    precio_tarjeta double precision,
    stock integer,
    imagen character varying(255) NOT NULL,
    rating double precision,
    num_opiniones integer,
    ean_upc character varying(255),
    tiempo_envio character varying(255),
    garantia text,
    condiciones text,
    devoluciones text
);


ALTER TABLE public.producto_definitivo OWNER TO postgres;

--
-- TOC entry 354 (class 1259 OID 18013)
-- Name: producto_definitivo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.producto_definitivo_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.producto_definitivo_id_seq OWNER TO postgres;

--
-- TOC entry 3818 (class 0 OID 0)
-- Dependencies: 354
-- Name: producto_definitivo_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.producto_definitivo_id_seq OWNED BY public.producto_definitivo.id;


--
-- TOC entry 349 (class 1259 OID 17607)
-- Name: producto_imagen; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producto_imagen (
    id integer NOT NULL,
    producto_id integer NOT NULL,
    url_imagen character varying(255) NOT NULL,
    orden integer
);


ALTER TABLE public.producto_imagen OWNER TO postgres;

--
-- TOC entry 348 (class 1259 OID 17606)
-- Name: producto_imagen_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.producto_imagen ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.producto_imagen_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 353 (class 1259 OID 17979)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    correo character varying(255) NOT NULL,
    nombre character varying(255) NOT NULL,
    password character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 352 (class 1259 OID 17978)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3637 (class 2604 OID 18017)
-- Name: producto_definitivo id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_definitivo ALTER COLUMN id SET DEFAULT nextval('public.producto_definitivo_id_seq'::regclass);


--
-- TOC entry 3803 (class 0 OID 17618)
-- Dependencies: 351
-- Data for Name: producto_color; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.producto_color (id, producto_id, nombre_color, codigo_hexadecimal) FROM stdin;
\.


--
-- TOC entry 3807 (class 0 OID 18014)
-- Dependencies: 355
-- Data for Name: producto_definitivo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.producto_definitivo (id, nombre, marca, categoria, almacenamiento, ram, procesador, precio_normal, precio, precio_tarjeta, stock, imagen, rating, num_opiniones, ean_upc, tiempo_envio, garantia, condiciones, devoluciones) FROM stdin;
1	iPhone 17 Pro Max 1TB	Apple	Smartphones Premium	1TB	12GB	A19 Pro Chip	8500	7999	7699	3	iphone_17_pm_1tb.png	5	8	0190199400015	24 horas	12 meses Apple	Garantía directa con fabricante.	7 días hábiles.
2	iPhone 17 Pro Max 512GB	Apple	Smartphones Premium	512GB	12GB	A19 Pro Chip	7500	6999	6799	5	iphone_17_pm_512.png	4.9	14	0190199400010	24 horas	12 meses Apple	Sujeto a disponibilidad.	7 días hábiles.
3	iPhone 17 Pro Max 256GB	Apple	Smartphones Premium	256GB	12GB	A19 Pro Chip	6800	6399	6199	8	iphone_17_pm_256.png	4.8	22	0190199400005	24 horas	12 meses Apple	Sujeto a disponibilidad.	7 días hábiles.
4	iPhone 17 Pro 512GB	Apple	Smartphones Premium	512GB	12GB	A19 Pro Chip	6700	6199	5999	7	iphone_17_p_512.png	4.8	19	0190199400040	24 horas	12 meses Apple	Caja sellada.	7 días hábiles.
5	iPhone 17 Pro 256GB	Apple	Smartphones Premium	256GB	12GB	A19 Pro Chip	6000	5499	5299	12	iphone_17_p_256.png	4.7	35	0190199400035	24 horas	12 meses Apple	Caja sellada.	7 días hábiles.
6	iPhone 17 Plus 256GB	Apple	Smartphones	256GB	8GB	A19 Chip	5400	4999	4799	10	iphone_17_plus_256.png	4.6	11	0190199400060	24 horas	12 meses Apple	Nuevos modelos.	7 días hábiles.
7	iPhone 17 256GB	Apple	Smartphones	256GB	8GB	A19 Chip	4900	4499	4299	15	iphone_17_256.png	4.6	28	0190199400085	24 horas	12 meses Apple	Nuevos modelos.	7 días hábiles.
8	iPhone 17 128GB	Apple	Smartphones	128GB	8GB	A19 Chip	4400	3999	3799	20	iphone_17_128.png	4.5	42	0190199400080	24 horas	12 meses Apple	Nuevos modelos.	7 días hábiles.
9	iPhone 16 Pro Max 1TB	Apple	Smartphones Premium	1TB	8GB	A18 Pro Chip	7900	7299	6999	4	iphone_16_pm_1tb.png	4.9	89	0190199399999	24 horas	12 meses Apple	Descuento con tarjeta.	7 días hábiles.
10	iPhone 16 Pro Max 512GB	Apple	Smartphones Premium	512GB	8GB	A18 Pro Chip	6900	6399	6199	6	iphone_16_pm_512.png	4.9	120	0190199399995	24 horas	12 meses Apple	Descuento con tarjeta.	7 días hábiles.
11	iPhone 16 Pro Max 256GB	Apple	Smartphones Premium	256GB	8GB	A18 Pro Chip	6200	5699	5499	14	iphone_16_pm_256.png	4.8	210	0190199399991	24 horas	12 meses Apple	Descuento con tarjeta.	7 días hábiles.
12	iPhone 16 Pro 512GB	Apple	Smartphones	512GB	8GB	A18 Pro Chip	6500	5900	5700	8	iphone_16_p_512.png	4.8	65	0190199399922	24 horas	12 meses Apple	Garantía local.	7 días hábiles.
13	iPhone 16 Pro 256GB	Apple	Smartphones	256GB	8GB	A18 Pro Chip	6000	5500	5300	10	iphone_16_p_256.png	4.9	45	0190199399990	24 horas	12 meses Apple	Garantía local.	7 días hábiles.
14	iPhone 16 Plus 256GB	Apple	Smartphones	256GB	8GB	A18 Chip	4900	4400	4200	11	iphone_16_plus_256.png	4.7	74	0190199399950	24 horas	12 meses Apple	Equipo libre.	7 días hábiles.
15	iPhone 16 256GB	Apple	Smartphones	256GB	8GB	A18 Chip	4500	3999	3799	18	iphone_16_256.png	4.6	115	0190199399920	24 horas	12 meses Apple	Equipo libre.	7 días hábiles.
16	iPhone 16 128GB	Apple	Smartphones	128GB	8GB	A18 Chip	4000	3499	3299	25	iphone_16_128.png	4.6	180	0190199399910	24 horas	12 meses Apple	Equipo libre.	7 días hábiles.
17	iPhone 15 Pro Max 512GB	Apple	Smartphones Premium	512GB	8GB	A17 Pro Chip	6100	5500	5300	8	iphone_15_pm_512.png	4.8	340	0190199320300	24 horas	12 meses Apple	Liquidación de stock.	7 días hábiles.
18	iPhone 15 Pro Max 256GB	Apple	Smartphones Premium	256GB	8GB	A17 Pro Chip	5500	4999	4799	12	iphone_15_pm_256.png	4.8	512	0190199320290	24 horas	12 meses Apple	Liquidación de stock.	7 días hábiles.
19	iPhone 15 Pro 256GB	Apple	Smartphones	256GB	8GB	A17 Pro Chip	5200	4800	4600	12	iphone_15_p_256.png	4.8	110	0190199320255	24 horas	12 meses Apple	Caja sellada.	7 días hábiles.
20	iPhone 15 Pro 128GB	Apple	Smartphones	128GB	8GB	A17 Pro Chip	4700	4299	4099	15	iphone_15_p_128.png	4.7	245	0190199320240	24 horas	12 meses Apple	Caja sellada.	7 días hábiles.
21	iPhone 15 256GB	Apple	Smartphones	256GB	6GB	A16 Bionic	4100	3699	3499	14	iphone_15_256.png	4.6	198	0190199320150	24 horas	12 meses Apple	Últimas unidades.	7 días hábiles.
22	iPhone 15 128GB	Apple	Smartphones	128GB	6GB	A16 Bionic	3600	3199	2999	30	iphone_15_128.png	4.6	420	0190199320140	24 horas	12 meses Apple	Últimas unidades.	7 días hábiles.
23	iPhone 14 Pro Max 256GB	Apple	Smartphones Premium	256GB	6GB	A16 Bionic	4600	3999	3799	5	iphone_14_pm_256.png	4.7	580	0190199320220	48 horas	12 meses Apple	Exhibición / Caja abierta.	7 días hábiles.
24	iPhone 14 Pro 128GB	Apple	Smartphones	128GB	6GB	A16 Bionic	3800	3500	3300	8	iphone_14_p_128.png	4.7	230	0190199320210	24 horas	12 meses Apple	Últimas unidades.	7 días hábiles.
25	iPhone 13 128GB	Apple	Smartphones	128GB	4GB	A15 Bionic	2900	2499	2350	40	iphone_13_128.png	4.7	980	0190199201104	24 horas	12 meses Apple	Precio de liquidación total.	7 días hábiles.
26	Samsung Galaxy S25 Ultra 1TB	Samsung	Celulares con IA	1TB	16GB	Snapdragon 8 Gen 4	6699	5599	5399	5	samsung_s25u_1tb.png	5	45	8806095820610	90 minutos zonas disp.	12 meses Samsung	Promoción Galaxy AI.	7 días de cambio.
27	Samsung Galaxy S25 Ultra 512GB	Samsung	Celulares con IA	512GB	12GB	Snapdragon 8 Gen 4	6199	5099	4899	10	samsung_s25u_512.png	4.9	88	8806095820608	90 minutos zonas disp.	12 meses Samsung	Promoción Galaxy AI.	7 días de cambio.
28	Samsung Galaxy S25 Ultra 256GB	Samsung	Celulares con IA	256GB	12GB	Snapdragon 8 Gen 4	5699	4599	4399	15	samsung_s25u_256.png	5	128	8806095820606	90 minutos zones disp.	12 meses Samsung	Promoción Galaxy AI.	7 días de cambio.
29	Samsung Galaxy S25 Plus 512GB	Samsung	Celulares con IA	512GB	12GB	Exynos 2500	5200	4600	4400	12	samsung_s25p_512.png	4.8	34	8806095820710	90 minutos	12 meses Samsung	Descuento con banco.	7 días de cambio.
30	Samsung Galaxy S25 Plus 256GB	Samsung	Celulares con IA	256GB	12GB	Exynos 2500	4800	4200	4000	20	samsung_s25p_256.png	4.8	56	8806095820700	90 minutos	12 meses Samsung	Aplica descuento NEXO.	7 días de cambio.
31	Samsung Galaxy S25 256GB	Samsung	Celulares con IA	256GB	8GB	Exynos 2500	3999	3499	3299	25	samsung_s25_256.png	4.7	62	8806095820800	24 horas	12 meses Samsung	Modelo base con IA.	7 días de cambio.
32	Samsung Galaxy S25 128GB	Samsung	Celulares con IA	128GB	8GB	Exynos 2500	3599	3199	2999	30	samsung_s25_128.png	4.6	92	8806095820810	24 horas	12 meses Samsung	Modelo base con IA.	7 días de cambio.
33	Samsung Galaxy Z Fold 6 512GB	Samsung	Smartphones Premium	512GB	12GB	Snapdragon 8 Gen 3	7999	7199	6899	4	samsung_fold6_512.png	4.9	41	8806095811550	24 horas	12 meses Samsung	Pantalla plegable dinámica.	7 días de cambio.
34	Samsung Galaxy Z Flip 6 256GB	Samsung	Smartphones Premium	256GB	12GB	Snapdragon 8 Gen 3	4999	4399	4199	8	samsung_flip6_256.png	4.8	105	8806095811660	24 horas	12 meses Samsung	Diseño compacto plegable.	7 días de cambio.
35	Samsung Galaxy S24 Ultra 512GB	Samsung	Smartphones	512GB	12GB	Snapdragon 8 Gen 3	5200	4499	4299	10	samsung_s24u_512.png	4.9	450	8806095810555	24 horas	12 meses Samsung	S Pen incluido.	7 días de cambio.
36	Samsung Galaxy S24 Ultra 256GB	Samsung	Smartphones	256GB	12GB	Snapdragon 8 Gen 3	4799	3999	3799	18	samsung_s24u_256.png	4.9	620	8806095810550	24 horas	12 meses Samsung	S Pen incluido.	7 días de cambio.
37	Samsung Galaxy S24 Plus 256GB	Samsung	Smartphones	256GB	12GB	Exynos 2400	3999	3299	3099	15	samsung_s24p_256.png	4.7	215	8806095810440	24 horas	12 meses Samsung	Liquidación de inventario.	7 días de cambio.
38	Samsung Galaxy S24 256GB	Samsung	Smartphones	256GB	8GB	Exynos 2400	3399	2799	2599	22	samsung_s24_256.png	4.6	310	8806095810330	24 horas	12 meses Samsung	Liquidación de inventario.	7 días de cambio.
39	Samsung Galaxy S23 Ultra 256GB	Samsung	Smartphones	256GB	8GB	Snapdragon 8 Gen 2	4200	3500	3300	5	samsung_s23u_256.png	4.9	340	8806095820555	24 horas	12 meses Samsung	Outlet / Liquidación.	7 días de cambio.
40	Samsung Galaxy S23 FE 256GB	Samsung	Gama Media Alta	256GB	8GB	Exynos 2200	2699	2199	1999	25	samsung_s23fe_256.png	4.5	185	8806095820221	24 horas	12 meses Samsung	Fan Edition oficial.	7 días de cambio.
41	Samsung Galaxy A56 5G 256GB	Samsung	Gama Media	256GB	8GB	Exynos 1580	2199	1899	1799	30	samsung_a56_256.png	4.7	12	8806095830111	24 horas	12 meses Samsung	Nuevo ingreso 2026.	7 días de cambio.
42	Samsung Galaxy A55 5G 256GB	Samsung	Gama Media	256GB	8GB	Exynos 1480	1999	1599	1499	45	samsung_a55_256.png	4.6	420	8806095829988	24 horas	12 meses Samsung	Best seller de gama media.	7 días de cambio.
43	Samsung Galaxy A55 5G 128GB	Samsung	Gama Media	128GB	8GB	Exynos 1480	1799	1399	1299	50	samsung_a55_128.png	4.5	510	8806095829980	24 horas	12 meses Samsung	Protección IP67.	7 días de cambio.
44	Samsung Galaxy A36 5G 128GB	Samsung	Gama Media	128GB	6GB	Snapdragon 6 Gen 3	1599	1299	1199	35	samsung_a36_128.png	4.5	8	8806095830222	24 horas	12 meses Samsung	Nuevo diseño 2026.	7 días de cambio.
45	Samsung Galaxy A35 5G 256GB	Samsung	Gama Media	256GB	8GB	Exynos 1380	1499	1199	1099	40	samsung_a35_256.png	4.5	145	8806095828855	24 horas	12 meses Samsung	Gran autonomía de batería.	7 días de cambio.
46	Samsung Galaxy A25 5G 128GB	Samsung	Gama Media Baja	128GB	6GB	Exynos 1280	1199	899	849	60	samsung_a25_128.png	4.4	230	8806095827744	24 horas	12 meses Samsung	Pantalla Super AMOLED.	7 días de cambio.
47	Samsung Galaxy A16 5G 128GB	Samsung	Gama de Entrada	128GB	6GB	Exynos 1330	949	799	749	70	samsung_a16_128.png	4.3	55	8806095830999	24 horas	12 meses Samsung	Actualizaciones aseguradas.	7 días de cambio.
48	Samsung Galaxy A15 4G 128GB	Samsung	Gama de Entrada	128GB	4GB	MediaTek Helio G99	799	629	589	90	samsung_a15_128.png	4.3	640	8806095825522	24 horas	12 meses Samsung	Económico y rendidor.	7 días de cambio.
49	Samsung Galaxy A05s 128GB	Samsung	Gama de Entrada	128GB	4GB	Snapdragon 680	699	529	499	110	samsung_a05s_128.png	4.2	780	8806095824411	24 horas	12 meses Samsung	Ideal para uso diario básico.	7 días de cambio.
50	Samsung Galaxy A04 64GB	Samsung	Gama de Entrada	64GB	4GB	MediaTek Helio P35	600	499	450	30	samsung_a04_64.png	4.3	85	8806095810101	24 horas	12 meses Samsung	Equipo básico.	7 días de cambio.
51	Xiaomi 14 Ultra 512GB	Xiaomi	Smartphones Premium	512GB	16GB	Snapdragon 8 Gen 3	5500	4999	4800	8	xiaomi_14u_512.png	4.9	62	6934177700011	48 horas	12 meses Xiaomi	Kit fotográfico incluido.	No aplica si está abierto.
52	Xiaomi 14T Pro 512GB	Xiaomi	Smartphones Premium	512GB	12GB	Dimensity 9300+	4199	3699	3499	14	xiaomi_14tp_512.png	4.8	48	6934177711223	24 horas	12 meses Xiaomi	Óptica Leica.	7 días con empaque original.
53	Xiaomi 14T 256GB	Xiaomi	Smartphones	256GB	12GB	Dimensity 8300 Ultra	3299	2899	2699	20	xiaomi_14t_256.png	4.7	75	6934177711220	24 horas	12 meses Xiaomi	Óptica Leica.	7 días con empaque original.
54	Xiaomi 14 512GB	Xiaomi	Smartphones Premium	512GB	12GB	Snapdragon 8 Gen 3	4499	3999	3799	10	xiaomi_14_512.png	4.8	130	6934177700555	24 horas	12 meses Xiaomi	Carga ultra rápida 90W.	7 días con empaque original.
55	Xiaomi 13 256GB	Xiaomi	Smartphones	256GB	8GB	Snapdragon 8 Gen 2	3500	2999	2850	15	xiaomi_13_256.png	4.6	120	6934177700022	48 horas	12 meses Xiaomi	No incluye cargador.	7 días máximo.
56	POCO F6 Pro 1TB	Xiaomi	Gama Alta Performance	1TB	16GB	Snapdragon 8 Gen 2	3299	2899	2749	18	xiaomi_pocof6p_1tb.png	4.9	145	6934177715522	24 horas	12 meses Xiaomi	Especial para gaming.	7 días de prueba.
57	POCO F6 Pro 512GB	Xiaomi	Gama Alta Performance	512GB	12GB	Snapdragon 8 Gen 2	2899	2499	2399	25	xiaomi_pocof6p_512.png	4.8	290	6934177715520	24 horas	12 meses Xiaomi	Especial para gaming.	7 días de prueba.
58	POCO F6 512GB	Xiaomi	Gama Alta Performance	512GB	12GB	Snapdragon 8s Gen 3	2499	2099	1999	30	xiaomi_pocof6_512.png	4.7	340	6934177715400	24 horas	12 meses Xiaomi	Máximo rendimiento/precio.	7 días de prueba.
59	POCO X6 Pro 512GB	Xiaomi	Gama Media Alta	512GB	12GB	Dimensity 8300 Ultra	1899	1549	1479	50	xiaomi_pocox6p_512.png	4.8	890	6934177714411	24 horas	12 meses Xiaomi	Pantalla CrystalRes AMOLED.	7 días de prueba.
60	POCO X6 512GB	Xiaomi	Gama Media	512GB	12GB	Snapdragon 7s Gen 2	1599	1299	1229	40	xiaomi_pocox6_512.png	4.6	410	6934177714300	24 horas	12 meses Xiaomi	Carga rápida 67W.	7 días de prueba.
61	POCO M6 Pro 512GB	Xiaomi	Gama Media Baja	512GB	12GB	MediaTek Helio G99-Ultra	1299	1049	999	65	xiaomi_pocom6p_512.png	4.6	560	6934177713300	24 horas	12 meses Xiaomi	Excelente almacenamiento.	7 días de prueba.
62	Redmi Note 14 Pro+ 512GB	Xiaomi	Gama Media Alta	512GB	12GB	Snapdragon 7s Gen 3	2399	1999	1899	15	xiaomi_rn14pp_512.png	4.8	25	6934177722114	24 horas	12 meses Xiaomi	Nuevo lanzamiento 2026.	7 días regular.
63	Redmi Note 14 Pro 256GB	Xiaomi	Gama Media	256GB	8GB	Dimensity 7300-Ultra	1899	1599	1499	28	xiaomi_rn14p_256.png	4.7	42	6934177722110	24 horas	12 meses Xiaomi	Resistente a caídas y agua.	7 días regular.
64	Redmi Note 13 Pro+ 512GB	Xiaomi	Gama Media Alta	512GB	12GB	Dimensity 7200-Ultra	2199	1749	1649	35	xiaomi_rn13pp_512.png	4.7	720	6934177719955	24 horas	12 meses Xiaomi	Pantalla curva IP68.	7 días regular.
65	Redmi Note 13 Pro 512GB	Xiaomi	Gama Media	512GB	12GB	Helio G99-Ultra	1699	1349	1279	48	xiaomi_rn13p_512.png	4.6	940	6934177719888	24 horas	12 meses Xiaomi	Cámara de 200MP.	7 días regular.
66	Redmi Note 13 Pro 4G 256GB	Xiaomi	Gama Media	256GB	8GB	Helio G99-Ultra	1399	1149	1079	60	xiaomi_rn13p_256.png	4.6	1150	6934177719880	24 horas	12 meses Xiaomi	Cámara de 200MP.	7 días de prueba.
67	Redmi Note 13 5G 256GB	Xiaomi	Gama Media	256GB	8GB	Dimensity 6080	1199	949	899	55	xiaomi_rn13_5g.png	4.5	430	6934177719550	24 horas	12 meses Xiaomi	Conectividad 5G económica.	7 días regular.
68	Redmi Note 13 4G 256GB	Xiaomi	Gama Media Baja	256GB	8GB	Snapdragon 685	999	799	749	120	xiaomi_rn13_4g_256.png	4.5	1850	6934177719440	24 horas	12 meses Xiaomi	Súper ventas global.	7 días regular.
69	Redmi Note 13 4G 128GB	Xiaomi	Gama Media Baja	128GB	6GB	Snapdragon 685	899	699	649	140	xiaomi_rn13_4g_128.png	4.4	2100	6934177719430	24 horas	12 meses Xiaomi	Súper ventas global.	7 días regular.
70	Redmi 14C 256GB	Xiaomi	Gama de Entrada	256GB	8GB	MediaTek Helio G81	799	649	599	80	xiaomi_r14c_256.png	4.4	28	6934177725544	24 horas	12 meses Xiaomi	Gran pantalla de 6.88\\".	7 días regular.
71	Redmi 14C 128GB	Xiaomi	Gama de Entrada	128GB	4GB	MediaTek Helio G81	699	549	499	95	xiaomi_r14c_128.png	4.3	47	6934177725540	24 horas	12 meses Xiaomi	Gran pantalla de 6.88\\".	7 días regular.
72	Redmi 13C 256GB	Xiaomi	Gama de Entrada	256GB	8GB	MediaTek Helio G85	749	589	549	150	xiaomi_r13c_256.png	4.4	1480	6934177718855	24 horas	12 meses Xiaomi	Líder en gama baja.	7 días regular.
73	Redmi 13C 128GB	Xiaomi	Gama de Entrada	128GB	4GB	MediaTek Helio G85	649	499	459	200	xiaomi_r13c_128.png	4.3	2300	6934177718850	24 horas	12 meses Xiaomi	Líder en gama baja.	7 días regular.
74	Redmi A3 128GB	Xiaomi	Gama de Entrada	128GB	4GB	MediaTek Helio G36	549	419	389	110	xiaomi_ra3_128.png	4.2	530	6934177717744	24 horas	12 meses Xiaomi	Diseño premium, costo bajo.	7 días regular.
75	Redmi A3 64GB	Xiaomi	Gama de Entrada	64GB	3GB	MediaTek Helio G36	479	369	339	130	xiaomi_ra3_64.png	4.1	620	6934177717740	24 horas	12 meses Xiaomi	El más accesible de la marca.	7 días regular.
76	Motorola Razr 50 Ultra 512GB	Motorola	Smartphones Premium	512GB	12GB	Snapdragon 8s Gen 3	5499	4899	4699	5	moto_razr50u_512.png	4.9	32	0723823211555	24 horas	12 meses Motorola	Plegable con pantalla externa gigante.	7 días directo.
77	Motorola Razr 50 256GB	Motorola	Smartphones Premium	256GB	8GB	Dimensity 7300X	4299	3799	3599	8	moto_razr50_256.png	4.7	24	0723823211550	24 horas	12 meses Motorola	Estilo icónico plegable.	7 días directo.
78	Motorola Edge 50 Ultra 1TB	Motorola	Smartphones Premium	1TB	16GB	Snapdragon 8s Gen 3	4499	3999	3799	6	moto_edge50u_1tb.png	4.8	41	0723823210444	24 horas	12 meses Motorola	Trasera de madera / cuero vegano.	7 días directo.
79	Motorola Edge 50 Pro 512GB	Motorola	Smartphones	512GB	12GB	Snapdragon 7 Gen 3	3499	2999	2849	14	moto_edge50p_512.png	4.7	68	0723823210333	24 horas	12 meses Motorola	Carga TurboPower de 125W.	7 días directo.
80	Motorola Edge 50 Fusion 256GB	Motorola	Gama Media Alta	256GB	8GB	Snapdragon 7 Gen 1	2299	1899	1799	22	moto_edge50f_256.png	4.6	94	0723823210222	24 horas	12 meses Motorola	Pantalla curva sin bordes.	7 días directo.
81	Motorola Edge 40 Neo 256GB	Motorola	Gama Media Alta	256GB	12GB	Dimensity 7030	1899	1499	1399	30	moto_edge40n_256.png	4.6	310	0723823209888	24 horas	12 meses Motorola	Colores Pantone oficiales.	7 días regular.
82	Motorola Moto G85 5G 256GB	Motorola	Gama Media	256GB	8GB	Snapdragon 6s Gen 3	1499	1199	1129	45	moto_g85_256.png	4.6	18	0723823215500	24 horas	12 meses Motorola	Lanzamiento reciente serie G.	7 días regular.
83	Motorola Moto G55 5G 256GB	Motorola	Gama Media	256GB	8GB	Dimensity 7025	1299	999	939	38	moto_g55_256.png	4.5	25	0723823215400	24 horas	12 meses Motorola	Excelente relación calidad precio.	7 días regular.
84	Motorola Moto G54 5G 256GB	Motorola	Gama Media	256GB	8GB	Dimensity 7020	1199	899	849	60	moto_g54_256.png	4.5	412	0723823214400	24 horas	12 meses Motorola	Gran batería de 5000 mAh.	7 días regular.
85	Motorola Moto G35 5G 128GB	Motorola	Gama Media Baja	128GB	4GB	Unisoc T760	1099	849	799	50	moto_g35_128.png	4.3	12	0723823215300	24 horas	12 meses Motorola	Pantalla FHD+ fluida.	7 días de fábrica.
86	Motorola Moto G24 Power 256GB	Motorola	Gama Media Baja	256GB	8GB	MediaTek Helio G85	999	769	719	85	moto_g24power_256.png	4.5	145	0723823214999	24 horas	12 meses Motorola	Super Batería de 6000 mAh.	7 días regular.
87	Motorola Moto G24 128GB	Motorola	Gama de Entrada	128GB	4GB	MediaTek Helio G85	799	599	559	110	moto_g24_128.png	4.3	230	0723823214888	24 horas	12 meses Motorola	Diseño moderno y ligero.	7 días regular.
88	Motorola Moto G14 128GB	Motorola	Gama de Entrada	128GB	4GB	Unisoc T616	699	529	489	140	moto_g14_128.png	4.2	580	0723823212255	24 horas	12 meses Motorola	Pantalla nítida Full HD+.	7 días de fábrica.
89	Motorola Moto G04s 128GB	Motorola	Gama de Entrada	128GB	4GB	Unisoc T606	599	469	439	160	moto_g04s_128.png	4.3	98	0723823215111	24 horas	12 meses Motorola	Cámara de 50MP accesible.	7 días de fábrica.
90	Motorola Moto G04 64GB	Motorola	Gama de Entrada	64GB	4GB	Unisoc T606	549	419	389	200	moto_g04_64.png	4.2	340	0723823215000	24 horas	12 meses Motorola	Muy económico y funcional.	7 días de fábrica.
91	Motorola Edge 40 256GB	Motorola	Smartphones	256GB	8GB	Dimensity 8020	2599	1999	1899	15	moto_edge40_256.png	4.6	520	0723823208555	48 horas	12 meses Motorola	Remanente de stock de fábrica.	7 días regular.
92	Motorola Moto G73 5G 256GB	Motorola	Gama Media	256GB	8GB	Dimensity 930	1699	1299	1199	20	moto_g73_256.png	4.4	410	0723823207444	24 horas	12 meses Motorola	Sonido Dolby Atmos.	7 días regular.
93	Motorola Moto G53 5G 128GB	Motorola	Gama Media Baja	128GB	6GB	Snapdragon 480+ 5G	1299	949	899	25	moto_g53_128.png	4.3	315	0723823206333	24 horas	12 meses Motorola	Liquidación de serie anterior.	7 días regular.
94	Motorola Moto G23 128GB	Motorola	Gama de Entrada	128GB	4GB	MediaTek Helio G85	899	649	599	40	moto_g23_128.png	4.2	490	0723823205222	24 horas	12 meses Motorola	Carga rápida TurboPower.	7 días regular.
95	Motorola Moto G13 128GB	Motorola	Gama de Entrada	128GB	4GB	MediaTek Helio G85	799	549	499	55	moto_g13_128.png	4.1	620	0723823204111	24 horas	12 meses Motorola	Altavoces estéreo.	7 días regular.
96	Motorola E14 64GB	Motorola	Gama de Entrada	64GB	2GB	Unisoc T606	449	349	319	120	moto_e14_64.png	4	15	0723823216000	24 horas	12 meses Motorola	Android Go Edition.	7 días de fábrica.
97	Motorola E13 64GB	Motorola	Gama de Entrada	64GB	2GB	Unisoc T606	399	299	279	180	moto_e13_64.png	4	840	0723823211111	24 horas	12 meses Motorola	Precio de remate absoluto.	7 días de fábrica.
98	Motorola ThinkPhone 256GB	Motorola	Smartphones Premium	256GB	8GB	Snapdragon 8+ Gen 1	3999	3299	3099	4	moto_thinkphone.png	4.7	55	0723823209555	48 horas	12 meses Motorola	Enfoque empresarial y seguridad.	7 días directo.
99	Honor 70 Lite 128GB	Honor	Gama Media	128GB	4GB	Snapdragon 480+	1200	999	899	25	Honor 70 Lite.png	4.5	45	6934177700033	24 horas	12 meses Honor	Equipo libre de fábrica.	Cambios dentro de los 7 días.
100	Xiaomi 13T Pro 512GB	Xiaomi	Smartphones Premium	512GB	12GB	Dimensity 9200+	3799	3199	2999	12	xiaomi_13tp_512.png	4.8	410	6934177717788	24 horas	12 meses Xiaomi	Gran descuento outlet.	7 días con empaque original.
\.


--
-- TOC entry 3801 (class 0 OID 17607)
-- Dependencies: 349
-- Data for Name: producto_imagen; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.producto_imagen (id, producto_id, url_imagen, orden) FROM stdin;
\.


--
-- TOC entry 3805 (class 0 OID 17979)
-- Dependencies: 353
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, correo, nombre, password) FROM stdin;
\.


--
-- TOC entry 3824 (class 0 OID 0)
-- Dependencies: 350
-- Name: producto_color_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.producto_color_id_seq', 1, false);


--
-- TOC entry 3825 (class 0 OID 0)
-- Dependencies: 354
-- Name: producto_definitivo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.producto_definitivo_id_seq', 1, false);


--
-- TOC entry 3826 (class 0 OID 0)
-- Dependencies: 348
-- Name: producto_imagen_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.producto_imagen_id_seq', 1, false);


--
-- TOC entry 3827 (class 0 OID 0)
-- Dependencies: 352
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- TOC entry 3641 (class 2606 OID 17622)
-- Name: producto_color producto_color_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_color
    ADD CONSTRAINT producto_color_pkey PRIMARY KEY (id);


--
-- TOC entry 3647 (class 2606 OID 18021)
-- Name: producto_definitivo producto_definitivo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_definitivo
    ADD CONSTRAINT producto_definitivo_pkey PRIMARY KEY (id);


--
-- TOC entry 3639 (class 2606 OID 17611)
-- Name: producto_imagen producto_imagen_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_imagen
    ADD CONSTRAINT producto_imagen_pkey PRIMARY KEY (id);


--
-- TOC entry 3643 (class 2606 OID 17987)
-- Name: users users_correo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_correo_key UNIQUE (correo);


--
-- TOC entry 3645 (class 2606 OID 17985)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3797 (class 0 OID 17618)
-- Dependencies: 351
-- Name: producto_color; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.producto_color ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3798 (class 0 OID 18014)
-- Dependencies: 355
-- Name: producto_definitivo; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.producto_definitivo ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3796 (class 0 OID 17607)
-- Dependencies: 349
-- Name: producto_imagen; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.producto_imagen ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3814 (class 0 OID 0)
-- Dependencies: 10
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- TOC entry 3815 (class 0 OID 0)
-- Dependencies: 351
-- Name: TABLE producto_color; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.producto_color TO anon;
GRANT ALL ON TABLE public.producto_color TO authenticated;
GRANT ALL ON TABLE public.producto_color TO service_role;


--
-- TOC entry 3816 (class 0 OID 0)
-- Dependencies: 350
-- Name: SEQUENCE producto_color_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.producto_color_id_seq TO anon;
GRANT ALL ON SEQUENCE public.producto_color_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.producto_color_id_seq TO service_role;


--
-- TOC entry 3817 (class 0 OID 0)
-- Dependencies: 355
-- Name: TABLE producto_definitivo; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.producto_definitivo TO anon;
GRANT ALL ON TABLE public.producto_definitivo TO authenticated;
GRANT ALL ON TABLE public.producto_definitivo TO service_role;


--
-- TOC entry 3819 (class 0 OID 0)
-- Dependencies: 354
-- Name: SEQUENCE producto_definitivo_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.producto_definitivo_id_seq TO anon;
GRANT ALL ON SEQUENCE public.producto_definitivo_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.producto_definitivo_id_seq TO service_role;


--
-- TOC entry 3820 (class 0 OID 0)
-- Dependencies: 349
-- Name: TABLE producto_imagen; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.producto_imagen TO anon;
GRANT ALL ON TABLE public.producto_imagen TO authenticated;
GRANT ALL ON TABLE public.producto_imagen TO service_role;


--
-- TOC entry 3821 (class 0 OID 0)
-- Dependencies: 348
-- Name: SEQUENCE producto_imagen_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.producto_imagen_id_seq TO anon;
GRANT ALL ON SEQUENCE public.producto_imagen_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.producto_imagen_id_seq TO service_role;


--
-- TOC entry 3822 (class 0 OID 0)
-- Dependencies: 353
-- Name: TABLE users; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.users TO anon;
GRANT ALL ON TABLE public.users TO authenticated;
GRANT ALL ON TABLE public.users TO service_role;


--
-- TOC entry 3823 (class 0 OID 0)
-- Dependencies: 352
-- Name: SEQUENCE users_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.users_id_seq TO anon;
GRANT ALL ON SEQUENCE public.users_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.users_id_seq TO service_role;


--
-- TOC entry 2397 (class 826 OID 16494)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- TOC entry 2398 (class 826 OID 16495)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- TOC entry 2396 (class 826 OID 16493)
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- TOC entry 2400 (class 826 OID 16497)
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- TOC entry 2395 (class 826 OID 16492)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- TOC entry 2399 (class 826 OID 16496)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO service_role;


-- Completed on 2026-07-15 03:31:30

--
-- PostgreSQL database dump complete
--

\unrestrict Ua4RAut8IeesMGs5ScRbjtI5mPZwQCuG8lITuc7r1jPj2OL65P32NzwnNFNoS3o

