spring.application.name=celular
server.port=${PORT:8080}

# =======================================================
# CONFIGURACIÓN DE CONEXIÓN A SUPABASE (POSTGRESQL)
# =======================================================
# Reemplaza TU_CONTRASEÑA por la contraseña real que creaste en Supabase.
# Si tu contraseña tiene caracteres especiales (como @, #, $, etc.), recuerda codificarla (percent-encode).
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.vbfemfynuewrzafcrxwt
spring.datasource.password=Tu1Ki7ZseQsrJNKCt

# Driver nativo de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# =======================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# =======================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Dialecto específico para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
