spring.application.name=celular
server.port=${PORT:8080}

# =======================================================
# CONFIGURACIÓN DE CONEXIÓN A sSUPABASE (POSTGRESQL)
# =======================================================
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.vbfemfynuewrzafcrxwt
spring.datasource.password=3SDvfyXnOO6IzLKB
spring.datasource.driver-class-name=org.postgresql.Driver

# =======================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# =======================================================
# 'update' creará las tablas automáticamente si no existen en Supabase
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false